import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import React, {ComponentProps} from "react";
import {
    NavigationMenu,
    NavigationMenuItem,
    NavigationMenuLink,
    NavigationMenuList, navigationMenuTriggerStyle
} from "@/components/ui/navigation-menu";
import Link from "next/link";
import {cn} from "@/lib/utils";
import {Icon} from "@iconify/react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

function NavLink({className, ...props}: ComponentProps<typeof Link>) {
    return <NavigationMenuItem>
        <NavigationMenuLink asChild className={navigationMenuTriggerStyle()}>
            <Link
                className={cn(className, "bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground/90")} {...props}/>
        </NavigationMenuLink>
    </NavigationMenuItem>;
}

function NavIcon({className, ...props}: React.AnchorHTMLAttributes<HTMLAnchorElement>) {
    return <NavigationMenuItem>
        <NavigationMenuLink asChild>
            <a target={"_blank"} className={cn(className, "px-0.5 hover:bg-transparent text-secondary")} {...props}/>
        </NavigationMenuLink>
    </NavigationMenuItem>;
}

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
        >
        <NavigationMenu className={"bg-primary text-primary-foreground"}>
            <NavigationMenuList>
                <NavLink href={"/#melanie"}>Melanie</NavLink>
            </NavigationMenuList>
            <NavigationMenuList>
                <NavLink href={"/#about"}>About</NavLink>

                <NavLink href={"/#skills"}>Skills</NavLink>
                <NavLink href={"/#proficiencies"}>Proficiencies</NavLink>
                <NavLink href={"/#projects"}>Projects</NavLink>
                <NavLink href={"/#experience"}>Experience</NavLink>
                <NavLink href={"/#contact"}>Contact</NavLink>
                <NavIcon href="https://github.com/tenchi-of-darkness">
                    <Icon className={"text-secondary size-6"} icon="line-md:github-twotone"/>
                </NavIcon>

                <NavIcon className={"mr-3"} href="https://www.linkedin.com/in/melanie-van-de-graaf/">
                    <Icon className={"text-secondary size-6"} icon="line-md:linkedin"/>
                </NavIcon>
            </NavigationMenuList>
        </NavigationMenu>
        {children}
        </body>
        </html>
    );
}
